### ISSUE TITLE
I got an issue 

### ISSUE THREAD

**Issue by madanmishra** [rdegges/btc-sms#2]
The "@angular/compiler-cli" package was not properly installed.

Error: The "@angular/compiler-cli" package was not properly installed.

    at Object.<anonymous> (C:\Users\madan\Desktop\gipsterapp\btc-sms\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\madan\Desktop\gipsterapp\btc-sms\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by rdegges** [comment]
Whatever error this is, it is not from this code. This is some unrelated angular thing I'm not at all familiar with.
